import:
  - ~/.alacritty_theme.yaml

window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: CaskaydiaCove NerdFont
    style: Regular

  bold:
    family: CaskaydiaCove NerdFont
    style: Bold

  italic:
    family: CaskaydiaCove NerdFont
    style: Italic

  bold_italic:
    family: CaskaydiaCove NerdFont
    style: Bold Italic

  size: 11
  offset:
    x: 0
    y: 0

cursor:
  style:
    shape: Underline
    blinking: Off

selection:
  save_to_clipboard: false
