import:
  - ~/.config/alacritty/themes/themes/afterglow.yaml

window:
  padding:
    x: 5
    y: 5
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 1

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic
  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 12
draw_bold_text_with_bright_colors: true

cursor:
  style:
    shape: Underline
    blinking: Off

selection:
  save_to_clipboard: false
