return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "eslint_d",
      "hadolint",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "vtsls",
    },
  },
}
